### ISSUE TITLE
My Personal Homepage

### ISSUE THREAD

**Issue by MorisR** [WebAhead/student-project-ideas#12]
## Name:
Moris R.

## Describe the problem you'd like to solve

Default homepages provided by different browsers are usually dull, unproductive and impersonal.
They usually contain only a search bar and your most-visited websites.

## Who are the stakeholders?

Everyone who seeks a more customizable and personal home page environment.

## What is currently being done to solve this problem?
- Change your default home page
- Open multiple tabs simultaneously
- Download more than one app on your phone to access different information

**Comment by fridabu** [comment]
something like this:
https://chrome.google.com/webstore/detail/the-new-tab-customize-you/ddjdamcnphfdljlojajeoiogkanilahc?hl=en

**Comment by DOOST13** [comment]
Hello! I have been using your Google chrome browser extension for a long time, I really liked it. But lately, you seem to have stopped supporting your product. And the app store is blocking your app with the wording "This extension violates the Chrome Web Store rules." I never found a decent alternative to replace your application. I beg you to correct this. I will be very grateful to you. Thank you!

**Comment by Karyum** [comment]
Hey @DOOST13 sorry to disappoint ya buddy, this repository is not for a chrome extension, it's meant for a coding bootcamp students who want to pitch their ideas 😅  .
Also we did not make that extension
