### ISSUE TITLE
offer your graphic designs 

### ISSUE THREAD

**Issue by MorisR** [WebAhead/student-project-ideas#13]
## Name:
Moris R.

## Who are the stakeholders?
- Everyone (businesses/start-ups/organizations/individuals/etc..) seeking to invest in a unique design(s) (e.g. logo, business card, poster, etc... )
- Amateur graphic designers seeking to promote/sell their work and gain work experience.

## Describe the problem you'd like to solve
* Designer perspective
    * Not finding clients
    * Experience requirements in job offers
    * Not having a portfolio
* Client perspective
    * The inability to produce/create your own designs
    * Purchasing a design on a budget
    * Purchasing a design in a timely manner

    

## What is currently being done to solve this problem?

- Hosting job offers and job interviews / applying to job offers
- Contacting a freelancer / offer your work as a freelancer

**Comment by fridabu** [comment]
I know at least about 10 services like that the most famous are:
https://www.freelancer.com/
And 
https://www.fiverr.com/

**Comment by MorisR** [comment]
Sure there might be other websites/platforms that offer solutions/solve the problem

But part of our task is to come up with a unique Interpretation of a solution for the provided issue

**Comment by MorisR** [comment]
> https://www.freelancer.com/
> And
> https://www.fiverr.com/

 these platforms in general target a wider range of audience, my envision of it was specifically towards graphics designers

A passible solution that someone could come up with:
1) I as a client enter an app/a website
2) I post a request for a logo and a poster
3) I put in the amount I'm willing to offer
4) graphics designers see the offer
5) they work on a solution and provide photos of their work and the price they're willing to take for it
6) the client scrolls through the provided solutions and chooses one, and then buys it or hires the designer
