### ISSUE TITLE
BuMa

### ISSUE THREAD

**Issue by fridabu** [WebAhead/student-project-ideas#17]
# Name

Farid

# Describe the problem you'd like to solve

Free-lance small business owners, such as yoga instructors and guitar teachers, need to manage their client scheduling and customer payments. There are a few current solutions to these issues, but they each have their downsides. There are comprehensive systems that are available for scheduling and payments, but they are generally designed with big business in mind; these systems are costly and offer more features than the free-lancer needs. There are individual apps for scheduling and payment that the free-lancer could use, but there is a loss of efficiency in trying to combine programs that are not designed to work together. Lastly, the free-lancer could use old-fashioned pen and paper, but this also inefficient timewise and leads to mistakes and lost revenue.

# Who are the stakeholders?

Free-lance small business owners, such as yoga instructors and guitar teachers.

#  User story.
Mario is a 30-year-old independent guitar teacher with 15 students.

On average, each student schedules a one-hour lesson each week.

When Mario logs into the website, he sees a calendar that shows the days on which he has lessons scheduled. If he clicks on any day, it shows a list of the students that are scheduled for that day. 

There is also a ‘Student’ section in the main menu of the website, in which a list of student profiles is kept.
Students that owe for the previous lesson appear with a red dot, while students which are up to date with their payments are shown with a green dot. 

Shireen is one of Mario’s students and she calls to schedule a lesson for Wednesday. Mario opens the app and clicks on Wednesday. He clicks the ‘+’ button which opens a form to set the appointment time. Mario selects the hour and clicks ‘Add’. 
An email is then sent to Shireen with the details of the lesson. 
After the lesson is completed, a PayPal request is sent to Shireen.

Marwan is a new student interested in guitar lessons with Mario. Mario creates a new profile for Marwan by clicking on the ‘Add New’ button in the app. This opens a form in which Mario can add the details of his new student Marwan

# Stretch goals:
- After each payment an electronic invoice sent to the student by mail
- In the end of each month a report with all the invoices sent to the accountant of the business

**Comment by jrd656** [comment]
I like this idea. I think it could be useful!

A friend of mine is a barber and he uses facebook and google / google maps for his bookings. Might be worth checking their services out for ideas/ comparison.
