### ISSUE TITLE
a platform to make students read instructions thoroughly 

### ISSUE THREAD

**Issue by okarem** [WebAhead/student-project-ideas#8]
**Name**
Karem

**Describe the problem you'd like to solve**
many times i've seen students rush to do a certain assignment, and in their hurry they don't read the instructions and do what they THINK the assignment wants instead of  what it ACTUALLY wants.
in this case: some students are writing **solutions** instead of **problems**

**Who are the stakeholders?**
- mentors/teachers
- students 
 
**What is currently being done to solve this problem?**
mentors type the important parts in **BOLD** , but no one is paying attention

**Comment by shiryz** [comment]
Closed for maintenance
