### ISSUE TITLE
Shopping Lists

### ISSUE THREAD

**Issue by jrd656** [WebAhead/student-project-ideas#9]
# Shopping List - WA5

#### Name
James

#### Describe the problem you'd like to solve
Israel is super expensive for groceries! Prices are also really variable. Could there be a shopping list platform that enables people to help each other quickly see if they could be getting their shopping cheaper elsewhere?

#### Who are the stakeholders?
Everyone who shops. Me. Future tourists who don't speak the language.

#### What is currently being done to solve this problem?
Prices around Haifa are super variable, which suggests the markets aren't working efficiently. Better informed consumers would change this.

**Comment by fridabu** [comment]
I know about:
https://www.pricez.co.il/
and 
https://www.mysupermarket.co.il/
But they don't have English interface

**Comment by jrd656** [comment]
Thanks Farid! I'll ask around and see what these platforms do. Can't understand a word of the Hebrew! XD
